### PR TITLE
Make textKey (default "content") configurable in XML-JSON conversion

### PR DESCRIPTION
**Pull request by jnothman**
The special handling of the key `"content"` in `XML.toString` results in highly unexpected behaviour in practice. Here is a patch that allows this key to be configurable. Indeed, `null` is a good value for most cases, and I suggest it be made the default.

### CODE REVIEW

**Comment by douglascrockford** [comment]
Please see the README.

**Comment by johnjaylward** [comment]
@jnothman We finally got around to trying out more configuration for the XML parser. Please see PR #412 and let us know if it meets your needs. It was based on this PR, so it should be close. Thanks.

**Comment by jnothman** [comment]
Sorry I'm not really available to comment. I can't recall the context in which I used this project.

**Comment by johnjaylward** [comment]
Thanks anyway

**Comment by jnothman** [comment]
I suppose that's a better response, at least, than Please see the README. I still can't see in the [README](https://github.com/stleary/JSON-java/blob/a75a060bc81bfe980bd172e985e3dd591e6c5e9b/README) of that time what I was possibly meant to see there.

**Comment by johnjaylward** [comment]
Yeah, at the time the readme mentioned he was looking for a maintainer

**Pull request closed without merging**
