### PR TITLE
Properly overrides the Exception class.

### PR DESCRIPTION
**Pull request by johnjaylward**
Overriding the exception class should not keep it's own ```cause``` field.

### CODE REVIEW

**Comment by stleary** [comment]
Can you say a few words about why this needs to be fixed?

**Comment by johnjaylward** [comment]
The Exception base class already has a variable to store the "cause" and the super.getCause() method already handles the cause properly. This pull request simplifies the implementation as well as creates less stack overhead when throwing an exception.

**Comment by stleary** [comment]
Moved to a branch commit and pull request. Please see https://github.com/douglascrockford/JSON-java/pull/161

**Comment by johnjaylward** [comment]
Not to be a jerk, but the way you are merging my changes loses the history that shows me as the committer. If you need to create personal branches to test pull requests that's fine, but you should merge the original pull request once approved to keep the proper committer history.

**Comment by johnjaylward** [comment]
I had already adjusted the date after seeing it modified in your PR. Not sure if that will affect the test.

**Comment by stleary** [comment]
Completed unit tests successfully. No local changes needed. Will leave this pull request open for a few days for comment.

**Comment by stleary** [comment]
**What problem does this code solve?**
The JSONException API already has a Throwable cause, initialized in the ctor and accessed via a getter.

**Changes to the API, code behavior, unit tests, or documentation?**
No

**Will this require a new release?**
No, this change will be rolled into the next release.

**Pull request merged**
