### PR TITLE
Update README 

### PR DESCRIPTION
**Pull request by stleary**
Release checkpoint and latest Maven release.

### CODE REVIEW

**Comment by stleary** [comment]
Oops, readme should be renamed to readme.md

**Comment by johnjaylward** [comment]
I'm wondering if the "Latest" release should just link to the entire group instead of the actual release number: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.json%22%20AND%20a%3A%22json%22

**Comment by stleary** [comment]
Fixed.

**Comment by johnjaylward** [comment]
Also, not sure if you want it, but #88 has more formatting enabled on the readme file.

**Comment by stleary** [comment]
True, but that was already declined once.

**Comment by stleary** [comment]
Rather than changing over to markup, will resubmit as a update to the original README.

**Pull request closed without merging**
